#SingleInstance Force
#Include "Libs.ahk"
#HotIf WinActive(GameProcessName)
#NoTrayIcon



; =======================================
; Clock management
; =======================================
; Global ClockCenterX := 1440
; Global ClockCenterY := 501
; Global ClockRadius := 119
; Global ClickOffset := 30
;
; All values are pregenerated by a script
; to reduce the amount of calculations
;

Global Angles := ["0", "4", "8", "12", "16", "20", "24", "28", "32", "36", "40", "44", "48", "52", "56", "60", "64", "68", "72", "76", "80", "84", "88", "92", "96", "100", "104", "108", "112", "116", "120", "124", "128", "132", "136", "140", "144", "148", "152", "156", "160", "164", "168", "172", "176", "180", "184", "188", "192", "196", "200", "204", "208", "212", "216", "220", "224", "228", "232", "236", "240", "244", "248", "252", "256", "260", "264", "268", "272", "276", "280", "284", "288", "292", "296", "300", "304", "308", "312", "316", "320", "324", "328", "332", "336", "340", "344", "348", "352", "356"]
Global XCoords := ["1440", "1448", "1457", "1465", "1473", "1481", "1488", "1496", "1503", "1510", "1516", "1523", "1528", "1534", "1539", "1543", "1547", "1550", "1553", "1555", "1557", "1558", "1559", "1559", "1558", "1557", "1555", "1553", "1550", "1547", "1543", "1539", "1534", "1528", "1523", "1516", "1510", "1503", "1496", "1488", "1481", "1473", "1465", "1457", "1448", "1440", "1432", "1423", "1415", "1407", "1399", "1392", "1384", "1377", "1370", "1364", "1357", "1352", "1346", "1341", "1337", "1333", "1330", "1327", "1325", "1323", "1322", "1321", "1321", "1322", "1323", "1325", "1327", "1330", "1333", "1337", "1341", "1346", "1352", "1357", "1364", "1370", "1377", "1384", "1392", "1399", "1407", "1415", "1423", "1432"]
Global YCoords := ["382", "382", "383", "385", "387", "389", "392", "396", "400", "405", "410", "415", "421", "428", "434", "441", "449", "456", "464", "472", "480", "489", "497", "505", "513", "522", "530", "538", "546", "553", "560", "568", "574", "581", "587", "592", "597", "602", "606", "610", "613", "615", "617", "619", "620", "620", "620", "619", "617", "615", "613", "610", "606", "602", "597", "592", "587", "581", "574", "568", "561", "553", "546", "538", "530", "522", "513", "505", "497", "489", "480", "472", "464", "456", "449", "441", "434", "428", "421", "415", "410", "405", "400", "396", "392", "389", "387", "385", "383", "382"]
Global XClickCoords := ["1440", "1470", "1440", "1410"]
Global TotalAngles := Angles.Length

Global HourAngles := ["180", "195", "210", "225", "240", "255", "270", "285", "300", "315", "330", "345", "0", "15", "30", "45", "60", "75", "90", "105", "120", "135", "150", "165"]
Global HourXCoords := ["1440", "1432", "1424", "1418", "1414", "1411", "1410", "1411", "1414", "1419", "1426", "1433", "1440", "1448", "1455", "1461", "1466", "1469", "1470", "1469", "1466", "1461", "1455", "1448"]
Global HourYCoords := ["531", "530", "527", "522", "515", "508", "500", "492", "485", "479", "475", "472", "471", "472", "475", "480", "486", "493", "501", "509", "516", "522", "527", "530"]

~NumpadDiv & Numpad2:: {
	SkipToTime(0)
}

~NumpadDiv & Numpad1:: {
	SkipToTime(3)
}

~NumpadDiv & Numpad4:: {
	SkipToTime(6)
}

~NumpadDiv & Numpad7:: {
	SkipToTime(9)
}

~NumpadDiv & Numpad8:: {
	SkipToTime(12)
}

~NumpadDiv & Numpad9:: {
	SkipToTime(15)
}

~NumpadDiv & Numpad6:: {
	SkipToTime(18)
}

~NumpadDiv & Numpad3:: {
	SkipToTime(21)
}

~NumpadDiv & Numpad5:: {
	If IsClockMenu()
		Return
	OpenMenu()
	MouseClick "Left", 45, 715 ; Clock icon
}

IsClockMenu() {
	Global
	Return PixelGetColor(1870, 50) = "0xECE5D8"
}

SkipToTime(NeededTime) {
	Global
	NextDay := GetKeyState("NumpadMult")
	AddOne := GetKeyState("Numpad0")
	SubtractOne := GetKeyState("NumpadDot")
	; Check if already in clock menu
	ClockMenuAlreadyOpened := IsClockMenu()
	If not ClockMenuAlreadyOpened {
		OpenMenu()

		MouseClick "Left", 45, 715 ; Clock icon
		WaitPixelColor("0xECE5D8", 1870, 50, 5000) ; Wait for the clock menu
	}
	
	Angle := GetCurrentAngle()
	Time := Integer(Round(AngleToTime(Angle)))
	
	If AddOne
		NeededTime += 1
	If SubtractOne
		NeededTime -= 1
	If (NeededTime < 0)
		NeededTime += 24
	Else If (NeededTime > 24)
		NeededTime -= 24
	
	Clicks := NeededTime - Time
	If (Clicks < 0)
		Clicks += 24
	If (NextDay and Time <= NeededTime)
		Clicks += 24
	Clicks := Round(Clicks / 6)
	
	Loop Clicks - 1 {
		Offset := Time + A_Index * 6 + 1
		If (Offset > 24)
			Offset -= 24
		ClickOnClock(HourXCoords[Offset], HourYCoords[Offset])
	}
	
	Offset := NeededTime + 1
	If (Offset > 24)
		Offset -= 24
	ClickOnClock(HourXCoords[Offset], HourYCoords[Offset])

	MouseClick "Left", 1440, 1000 ; "Confirm" button
	
	If ClockMenuAlreadyOpened
		Return

	Sleep 100
	WaitPixelColor("0xECE5D8", 1870, 50, 30000) ; Wait for the clock menu

	Send "{Esc}"
	WaitMenu()

	Send "{Esc}"
}

GetCurrentAngle() {
	Global
	Loop TotalAngles {
		If (PixelGetColor(XCoords[A_Index], YCoords[A_Index]) = "0xECE5D8")
			Return Angles[A_Index]
	}
	Return 0
}

AngleToTime(Angle) {
	Time := Angle * 24 / 360 + 12
	If Time > 24
		Time -= 24
	Return Time
}

ClickOnClock(X, Y) {
	MouseClick "Left", X, Y, , , "Down"
	Sleep 50
	MouseClick "Left", X, Y, , , "Up"
	Sleep 100
}
